### ISSUE TITLE
NoBackend() problem

### ISSUE THREAD

**Issue by miqbal23** [tuwien-musicir/DL_MIR_Tutorial#2]
Many people are experiencing `NoBackend()` error when running Load Audio files cell inside the Notebook. This is caused by `audioread` not having the backend available for processing the audio

Maybe you could add this info from librosa GitHub about providing the backend : https://github.com/librosa/librosa/#hints-for-the-installation

**Comment by audiofeature** [comment]
Thanks for pointing this out. We now added a section on how to install an mp3 decoder here:

https://github.com/tuwien-musicir/DL_MIR_Tutorial#install-mp3-decoder

**Comment by audiofeature** [comment]
let us know if this solves the problem , or whether there are other steps necessary

**Comment by miqbal23** [comment]
thank you for the solution. it worked for me now

i also found another alternative from librosa Github : https://github.com/librosa/librosa/#hints-for-the-installation

**Comment by audiofeature** [comment]
yes, its an equal solution
