### ISSUE TITLE
Typo in Custom Model

### ISSUE THREAD

**Issue by miqbal23** [tuwien-musicir/DL_MIR_Tutorial#3]
I found a typo at **Custom Model** section, 2nd cell
```
# Layer 2
if use_layers == 2:
    model.add(Convolution2D(conv_filters, 3, 3, activation=cnn_activation, border_mode='valid', input_shape=input_shape))
    #model.add(BatchNormalization())
    model.add(Activation(cnn_act)) <---
    model.add(MaxPooling2D(pool_size=(2, 2)))
```
shouldn't `cnn_act` be `cnn_activation`? Because in the previous cell there's a variable called `cnn_activation` that contains the information needed for activation function of the layer

**Comment by audiofeature** [comment]
That's correct. 
However it is already present in Convolution2D(conv_filters, 3, 3, activation=cnn_activation, ...)
so this line can be removed / commented out.
(thats what i did in the latest version available in the repo).
